### PR TITLE
Update ha-navbar-position.js to allow compatibility with HA 2023.04 +

### PR DESCRIPTION
**Pull request by Greenphlem**
The header class has changed from `app-header` to `.header` , this PR changes one line to fix the issues with this project not working with versions of HA > 2023.03. Credit for this goes to [eZaz](https://forum.hacf.fr/t/modification-css-de-ha/23237/4?u=clemalex)

### CODE REVIEW

**Comment by zazDuTuitisme** [comment]
Thx for the PR @Greenphlem ;)

**Comment by alhafoudh** [comment]
Works, merge and release please :)

**Comment by n4rrOx** [comment]
Hm... Changed app-header to .header in line 51 of file:
config/www/community/ha-navbar-position/ha-navbar-position.js

But still not possible to move the navbar...tested in the HA-app as well as mobile Chrome Browser.
Also restarted several Times.

Any advice?
Thanks!

**Comment by kmil4** [comment]
is this going to be merged? I'm really missing it

**Comment by javawizard** [comment]
Hey everyone, sorry for totally ghosting!

I'm going to upgrade my HA instances to 2023.5 over the weekend - then I'll test this out and merge it.

Side note: I'd love to not be the bottleneck for stuff like this - if anyone's up for being added as a contributor and vetting PRs, let me know!

**Comment by Clement-B** [comment]
Using last version of HA (2023.5.4), it will need another change to fix paddings.

Here is the fix I applied if it can help :

Fix : 
```js
    // Replace this
    let contentContainer = this.huiRootElement?.querySelector("#layout")?.shadowRoot?.querySelector("#contentContainer");
    // by this
    let contentContainer = this.huiRootElement?.querySelector("#view");
```

**Comment by kmil4** [comment]
@javawizard can you please, please merge 🙏or give me write access and I will.

**Comment by javawizard** [comment]
Wish granted :) Sorry that took me so long!

**Pull request merged**
